# SOLUTION FILE - Don't peek until you've tried it yourself!
# Copy this to .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linter (ruff)
        run: ruff check .

      - name: Run tests (pytest)
        run: pytest -v

      # SECRET MISSION: Build artifact
      - name: Build distribution
        run: python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
